myapp/myapp/controllers/examples.py
#!/usr/bin/env python
# encoding: utf-8

from __future__ import print_function, division, absolute_import
from flask import current_app, Blueprint, render_template, abort, g
from flask import session as current_session, request, redirect, url_for, jsonify
import numpy as np
from . import processRequest

# this is a Blueprint.  It helps you modularize your app.
example_page = Blueprint("example_page", __name__)


@example_page.route('/examples/')
def example():
    output = {}
    output['title'] = 'MyApp Examples'
    output['page'] = 'example'

    # Set some variable in g
    g.ra = 2345.456
    dothis()

    # thing to split in browser
    output['splitme'] = 'I-don"t-want-to-be-split-up!'

    # make some list data
    output['listdata'] = ['DOG', 'CAT', 'HORSE', 'PIG']

    # make some table data
    output['tabledata'] = {'head': ['A', 'B'], 'body': [(1, 4), (2, 5), (3, 6)]}

    return render_template('examples.html', **output)


# this function is called from the main example route, and can access the g
def dothis():
    ra = g.get('ra', None)
    print('I am a variable stored in g: ra', ra)


@example_page.route('/getrandomnumber/', methods=['POST'], endpoint='getrandom')
def getrandom():
    ''' Generates a Random Number

    This is function designed primarily with a handling an
    asynchronous javascript request from your browser.  It must
    return a JSON object

    Parameters:
        start (int): the starting value
        end (int): the ending value

    Returns:
        result (dict):
            A python dictionary containing parameters that has been
            turned into a JSON object with Jsonify
    '''
    result = {}
    result['number'] = None
    result['error'] = None
    result['status'] = -1

    # get any form parameters
    form = processRequest(request)
    start = form.get('start', None)
    end = form.get('end', None)

    # Generate a random number based on input
    if all([start, end]):
            result['number'] = np.random.randint(int(start), int(end))
    elif any([start, end]):
        result['error'] = 'Could not generate number!'
    else:
        result['number'] = np.random.random()

    # Check number and set status accordingly
    if result['number']:
        result['status'] = 1
    else:
        val = 'End' if start and not end else 'Start' if end and not start else None
        errmsg = '{0}ing number not specified'.format(val)
        result['error'] = '{0}: {1}'.format(result['error'], errmsg)

    # jsonify will take your contents and convert it to a JSON format using json.dumps
    # it accepts multiple args and kwargs, but I like to package things together
    return jsonify(result=result)


@example_page.route('/changesession/', methods=['POST'], endpoint='changesession')
def changesession():
    result = {}
    result['error'] = None
    result['status'] = -1

    # get any form parameters
    form = processRequest(request)
    active = form.get('isactive', None)

    # set the session variable
    if active == 'true':
        print('setting loadcat false')
        current_session['loadcat'] = False
    elif active == 'false':
        print('setting loadcat true')
        current_session['loadcat'] = True

    return jsonify(result=result)

myapp/myapp/templates/examples.html
{% extends "layout.html" %}
{% set active_page = active_page|default("examples") %}

{# Import code from macros to reuse in places #}
{% from 'macros.html' import listgroup, table %}


{% block body %}

<div class='well'>
    <div class='row'>
        <div class='col-md-12 col-md-offset-5'>
            <h1>Examples <small>Offset this with a class</small></h1>
        </div>
    </div>
     <div class='row'>
        <div class='col-md-12'>
            <h2 class='pull-left'>Force text left</h2>
            <h2 class='pull-right'>Force text right</h2>
        </div>
    </div>
    <div class='row'>
        <div class='col-md-12 col-md-offset-4'>
            <h4 id='split'>custom jinja filter: {{splitme|split('-')}}</h4>
        </div>
    </div>
</div>

{# Some Javascript and Input Examples #}
<div class='well'>
    <div class='row'>
        <div class='col-md-12'>
            <h4>Here are some Buttons that do Javascript things</h4>
        </div>
        <div class='col-md-4'>
            {# Bootstrap Form #}
            <form class="form-inline" role='form' id='randomform'>
              <div class="form-group">
                <label class="sr-only" for="exampleInputAmount">Amount (in dollars)</label>
                <div class="input-group">
                  <input type="text" class="form-control input-sm" name='start' id="start" placeholder="Start">
                  <div class="input-group-addon">To</div>
                  <input type="text" class="form-control input-sm" name='end' id="end" placeholder="End">
                </div>
              </div>
              {# A normal form submission type='submit' will cause a page change/reload. We don't want that here.
              Change type="submit" to type="button"
              #}
              <button type="button" class="btn btn-primary" id='randombutton'>Get a Random Number</button>
            </form>

            {# Here is the output of the RandomNumber #}
            <div id='randomoutput'></div>

            {# Here is a List group #}
            <ul class="list-group">
              <li class="list-group-item">Try no numbers</li>
              <li class="list-group-item">Try a number and a letter</li>
              <li class="list-group-item">Try two numbers </li>
              <li class="list-group-item">Try only one number</li>
            </ul>
        </div>
        <div class='col-md-4'>
            {# You can set variables inside jinja2 #}
            {% set offtext = 'Change a Flask Session Variable to toggle loadcat' %}
            {% set ontext = 'Toggle loadcat off' %}

            {% if not session.loadcat %}
            <button type="button" class="btn btn-primary {{'active' if session.loadcat else ''}}" id='changesession' data-toggle='button' aria-pressed="{{'true' if session.loadcat else 'false'}}" data-complete-text='{{ontext}}'>{{offtext}}</button>
            {% else %}
            <button type='button' class='btn btn-danger' disabled='disabled'>My button is disabled :(</button>
            {% endif %}

        </div>
    </div>
</div>

{# Some Macro and Loop Examples #}
<div class='well'>
    <div class='row'>
        <div class='col-md-4'>
            {{listgroup(listdata, 'animals')}}
        </div>
        <div class='col-md-4'>
            <h3>I'm a macro table</h3>
            {{table(tabledata)}}
        </div>
    </div>
</div>

{% endblock body %}

<!-- JS Code -->
{% block code %}
    {# Load the javascript source code #}
    <script type='text/javascript' src="{{url_for('static',filename='js/example.js')}}"></script>
    <script type='text/javascript'>
        // instantiate the Example javascript object.
        // A Javascript Object MUST be called with the new keyword.
        var exam = new Example();
        console.log('here is my exam object', exam);
        // Use a public method on our new object
        var z = exam.add(5, 3);
        console.log("z is", z);
    </script>
{% endblock code %}

myapp/myapp/templates/footer.html
<div class="container-fluid" id="footer-content">

    <footer>
       <nav class="navbar navbar-default">
            <div class='row'>
                <div class='col-md-12 col-md-offset-5'>
                    <h4>I'm a footer</h4>
                </div>
            </div>
        </nav>

    </footer>

</div>

myapp/myapp/templates/header.html
<nav class="navbar navbar-default">
    <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{url_for('index_page.index')}}">My App</a>
        </div>

        <div class="navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a>This is the header (templates/header.html)</a></li>
                <li class="{{'active' if active_page=='examples'}}"><a href="{{url_for('example_page.example')}}">Examples</a></li>
            </ul>
        </div>
    </div>
</nav>

myapp/myapp/templates/index.html
{# This is a Jinja2 comment #}

{# In Jinja2, layout is the page from which all others inherit, using extends.  It mostly imports external libraries #}
{% extends "layout.html" %}

{# In Jinja2, this lets the header know which page is the active page (to highlight it) #}
{% set active_page = active_page|default("index") %}

{# insert custom header files here, like specialized css #}
{% block csshead %}
{% endblock csshead %}

{# here you are defining the content that gets inserted into the layout body block #}
{% block body %}

<div class='well'> {# well is a bootstrap class that adds the grey box #}
    {# Variables in Jinja2 are accessed via double "{{}}" #}
    <h1>{{mytext}} on the {{page|upper}} page</h1>
    <h2>The url for my page is {{myurl}}</h2>
    <h3>Cat loading is set to {{loadcat}}. <small>You can set defaults for variables that don't exist {{myvar|default("Not set")}}</small></h3>
    <h4><a href='{{url_for("index_page.wrongpage")}}'>Click Me!</a> I'm a page that doesn't exist.</h4>
    <h5>I'm so small :( <small>I'm even smaller....</small></h5>
</div>

{# you can write conditional template blocks with the %% statements #}
{% if session.loadcat %}
    <div class='well'>
        <div class='row'>
            <div class='col-md-5 col-xs-2'>
                <img class='img-responsive' src='{{url_for("static", filename="images/catlightning.jpg")}}' alt='My Image'>
            </div>
        </div>
    </div>
{% else %}
    <div class='well'>
        <h5>I'm the else clause.  Cat loading is off</h5>
    </div>
{% endif %}

{% endblock body %}

myapp/myapp/templates/layout.html
<!DOCTYPE html>
{% set active_page = active_page|default("myapp") %}

<html lang="en">

<!-- Html header -->
<head>
    <!-- CSS sources-->
    {# include your css files #}
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="shortcut icon" href="{{url_for('static',filename='images/favicon.ico')}}" type="image/x-icon" />
    {% block csshead %}{% endblock csshead %}

    <!-- Javascript sources-->
    {# include your js files #}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {% block jshead %}{% endblock jshead %}
</head>

<!-- Html body -->
<body class='{{page|default("myapp")}}'>

    <!-- Add a header -->
    {# the include tells Jinja2 to import the contents of the named file directly in this location #}
    {% include 'header.html' %}

    <!-- Main Body -->
    <div class="container-fluid" id="content">
        {% block body %}{% endblock body %}
    </div>

    <!-- Add a Footer -->
    {% include 'footer.html' %}

    <!-- Javascript Code Block -->
    {# Put the code block at the bottom so it only loads once the rest of the page has loaded #}
    {# Load the Javascsript code to use Flask url_for #}
    {{ JSGlue.include() }}
    {% block code %}{% endblock code %}
</body>
</html>

myapp/myapp/templates/macros.html
{# Resuable code can be imported elsewhere #}


{# List Group #}
{% macro listgroup(mylist, id) %}

  <h3>{{id|upper}}</h3>
  <ul class="list-group" id='list_{{id}}'>
    {% for item in mylist %}
    <li class="list-group-item" id='{{item|lower}}'>{{item}}</li>
    {% endfor %}
  </ul>

{% endmacro %}


{# Table Macro #}
{% macro table(data) %}

    <table class='table table-responsive table-condensed table-striped'>
        <thead>
            {% for col in data.head %}
            <th>{{col}}</th>
            {% endfor %}
        </thead>
        <tbody>
            {% for rows in data.body %}
                    <tr><td>{{rows[0]}}</td><td>{{rows[1]}}</td></tr>
            {% endfor %}
        </tbody>
    </table>

{% endmacro %}